version: '2'
services:
   telegraf:
      image: "telegraf"
      ports:
        - "8092:8092/udp"
        - "8125:8125/udp"
        - "8094:8094"
      volumes:
        - /sys/fs:/sys/fs:ro
        - /var/run/api.pid:/var/run/api.pid
        - /home/ht/monitor-compose/root/etc/telegraf:/etc/telegraf
        - /proc/22753:/root/proc/22753
        - /:/rootfs:ro
      privileged: true
   influxdb:
      image: "influxdb"
      ports:
        - "8086:8086"
      volumes:
        - /home/ht/monitor-compose/root/etc/influxdb:/etc/influxdb
        - /home/ht/monitor-compose/root/var/lib/influxdb:/var/lib/influxdb
   kapacitor:
      image: "kapacitor"
      ports:
        - "9092:9092"
      volumes:
        - /home/ht/monitor-compose/root/etc/kapacitor:/etc/kapacitor
        - /home/ht/monitor-compose/root:/root
        - /home/ht/monitor-compose/root/var/lib/kapacitor:/var/lib/kapacitor
      environment:
        HOSTNAME: "172.21.78.50"
   chronograf:
      image: "chronograf"
      ports:
        - "8888:8888"
