version: '2'
services:
   influxdb:
      image: "influxdb"
      ports:
        - "8086:8086"
      volumes:
        - /home/heting/monitor-compose/root/etc/influxdb:/etc/influxdb
        - /home/heting/monitor-compose/root/var/lib/influxdb:/var/lib/influxdb
   chronograf:
      image: "chronograf"
      ports:
        - "8888:8888"
